CREATE TABLE CATEGORIA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORIA (NOME) VALUES ('Lazer');
INSERT INTO CATEGORIA (NOME) VALUES ('Alimentação');
INSERT INTO CATEGORIA (NOME) VALUES ('Supermercado');
INSERT INTO CATEGORIA (NOME) VALUES ('Farmácia');
INSERT INTO CATEGORIA (NOME) VALUES ('Outros');
INSERT INTO CATEGORIA (NOME) VALUES ('Informática');
INSERT INTO CATEGORIA (NOME) VALUES ('Cartão de Crédito');
INSERT INTO CATEGORIA (NOME) VALUES ('Parques');
INSERT INTO CATEGORIA (NOME) VALUES ('Eventos');
INSERT INTO CATEGORIA (NOME) VALUES ('Empréstimo');
INSERT INTO CATEGORIA (NOME) VALUES ('Serviços Imobiliários');
INSERT INTO CATEGORIA (NOME) VALUES ('Serviços de crédito');
INSERT INTO CATEGORIA (NOME) VALUES ('Obras');
INSERT INTO CATEGORIA (NOME) VALUES ('Automóvel');
INSERT INTO CATEGORIA (NOME) VALUES ('Viagem');

