CREATE TABLE PESSOA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    CEP VARCHAR(8),
    LOGRADOURO VARCHAR(20),
    NUMERO VARCHAR(5),
    COMPLEMENTO VARCHAR(20),
    BAIRRO VARCHAR(20),
    CIDADE VARCHAR(20),
    UF VARCHAR(2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;