
CREATE TABLE LANCAMENTO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGAMENTO DATE,
	VALOR DECIMAL(10,2) NOT NULL,
	OBSERVACAO VARCHAR(100),
	TIPO VARCHAR(20) NOT NULL,
	ID_CATEGORIA BIGINT(20) NOT NULL,
	ID_PESSOA BIGINT(20) NOT NULL,
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;