CREATE TABLE USUARIO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA  VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PERMISSAO (
	ID BIGINT(20) PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE USUARIO_PERMISSAO (
	ID_USUARIO BIGINT(20) NOT NULL,
	ID_PERMISSAO BIGINT(20) NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_PERMISSAO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO(ID)	
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

