INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('JOÃO SILVA', 'RUA DO ABACAXI', '10', NULL, 'BRASIL', '38400120', 'UBERLÂNDIA', 'MG', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('MARIA RITA', 'RUA DO SABIÁ', '110', 'APTO 101', 'COLINA', '11400120', 'RIBEIRÃO PRETO', 'SP', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('PEDRO SANTOS', 'RUA DA BATERIA', '23', NULL, 'MORUMBI', '54212120', 'GOIÂNIA', 'GO', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('RICARDO PEREIRA', 'RUA DO MOTORISTA', '123', 'APTO 302', 'APARECIDA', '38400120', 'SALVADOR', 'BA', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('JOSUÉ MARIANO', 'AV RIO BRANCO', '321', NULL, 'JARDINS', '56400120', 'NATAL', 'RN', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('PEDRO BARBOSA', 'AV BRASIL', '100', NULL, 'TUBALINA', '77400120', 'PORTO ALEGRE', 'RS', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('HENRIQUE MEDEIROS', 'RUA DO SAPO', '1120', 'APTO 201', 'CENTRO', '12400120', 'RIO DE JANEIRO', 'RJ', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('CARLOS SANTANA', 'RUA DA MANGA', '433', NULL, 'CENTRO', '31400120', 'BELO HORIZONTE', 'MG', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('LEONARDO OLIVEIRA', 'RUA DO MÚSICO', '566', NULL, 'SEGISMUNDO PEREIRA', '38400001', 'UBERLÂNDIA', 'MG', TRUE);
INSERT INTO PESSOA (NOME, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, UF, ATIVO) VALUES ('ISABELA MARTINS', 'RUA DA TERRA', '1233', 'APTO 10', 'VIGILATO', '99400120', 'MANAUS', 'AM', TRUE);


INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Salário mensal', '2017-06-10', null, 6500.00, 'Distribuição de lucros', 'RECEITA', 1, 1);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Bahamas', '2017-02-10', '2017-02-10', 100.32, null, 'DESPESA', 2, 2);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Top Club', '2017-06-10', null, 120, null, 'RECEITA', 3, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('CEMIG', '2017-02-10', '2017-02-10', 110.44, 'Geração', 'RECEITA', 3, 4);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('DMAE', '2017-06-10', null, 200.30, null, 'DESPESA', 3, 5);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Extra', '2017-03-10', '2017-03-10', 1010.32, null, 'RECEITA', 4, 6);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Bahamas', '2017-06-10', null, 500, null, 'RECEITA', 1, 7);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Top Club', '2017-03-10', '2017-03-10', 400.32, null, 'DESPESA', 4, 8);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Despachante', '2017-06-10', null, 123.64, 'Multas', 'DESPESA', 3, 9);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Pneus', '2017-04-10', '2017-04-10', 665.33, null, 'RECEITA', 5, 10);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Café', '2017-06-10', null, 8.32, null, 'DESPESA', 1, 5);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Eletrônicos', '2017-04-10', '2017-04-10', 2100.32, null, 'DESPESA', 5, 4);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Instrumentos', '2017-06-10', null, 1040.32, null, 'DESPESA', 4, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Café', '2017-04-10', '2017-04-10', 4.32, null, 'DESPESA', 4, 2);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, ID_CATEGORIA, ID_PESSOA) VALUES ('Lanche', '2017-06-10', null, 10.20, null, 'DESPESA', 4, 1);
 